DROP TABLE AplicacaoProduto CASCADE CONSTRAINTS;
DROP TABLE CadernoDeCampo CASCADE CONSTRAINTS;
DROP TABLE Cultura CASCADE CONSTRAINTS;
DROP TABLE Edificio CASCADE CONSTRAINTS;
DROP TABLE Elemento CASCADE CONSTRAINTS;
DROP TABLE ElementoFicha CASCADE CONSTRAINTS;
DROP TABLE EstacaoMeteorologica CASCADE CONSTRAINTS;
DROP TABLE FatorDeProducao CASCADE CONSTRAINTS;
DROP TABLE Fertilizacao CASCADE CONSTRAINTS;
DROP TABLE FichaTecnica CASCADE CONSTRAINTS;
DROP TABLE ModoFertilizicao CASCADE CONSTRAINTS;
DROP TABLE Operacao CASCADE CONSTRAINTS;
DROP TABLE Parcela CASCADE CONSTRAINTS;
DROP TABLE Plantacao CASCADE CONSTRAINTS;
DROP TABLE Quinta CASCADE CONSTRAINTS;
DROP TABLE RegistoSensor CASCADE CONSTRAINTS;
DROP TABLE Sensor CASCADE CONSTRAINTS;
DROP TABLE TipoEdificio CASCADE CONSTRAINTS;
DROP TABLE TipoOperacao CASCADE CONSTRAINTS;
DROP TABLE TipoSensor CASCADE CONSTRAINTS;

CREATE TABLE APLICACAOPRODUTO (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DESIGNACAO VARCHAR2(255) NOT NULL,
  FATORDEPRODUCAOID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CADERNODECAMPO (
  ID NUMBER(10) GENERATED AS IDENTITY,
  QUINTAID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CULTURA (
  NOMECOMUM VARCHAR2(255) NOT NULL,
  VARIEDADE VARCHAR2(255) NOT NULL,
  ESPECIE VARCHAR2(255) NOT NULL,
  TIPOCULTURA VARCHAR2(255) NOT NULL CHECK(TIPOCULTURA IN ('Permanente', 'Temporária')),
  PODA VARCHAR2(255),
  FLORACAO VARCHAR2(255),
  COLHEITA VARCHAR2(255),
  SEMENTEIRA VARCHAR2(255),
  PRIMARY KEY (NOMECOMUM, VARIEDADE)
);

CREATE TABLE EDIFICIO (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL,
  AREA NUMBER(10),
  UNIDADE VARCHAR2(255),
  QUINTAID NUMBER(10) NOT NULL,
  TIPOEDIFICIODESIGNACAO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ELEMENTO (
  DESIGNACAO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (DESIGNACAO)
);

CREATE TABLE ELEMENTOFICHA (
  FICHATECNICAID NUMBER(10) NOT NULL,
  ELEMENTODESIGNACAO VARCHAR2(255) NOT NULL,
  QUANTIDADE NUMBER(10) NOT NULL,
  UNIDADE VARCHAR2(255) NOT NULL,
  PRIMARY KEY (FICHATECNICAID, ELEMENTODESIGNACAO)
);

CREATE TABLE ESTACAOMETEOROLOGICA (
  ID NUMBER(10) GENERATED AS IDENTITY,
  QUINTAID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE FATORDEPRODUCAO (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DESIGNACAO VARCHAR2(255) NOT NULL,
  FABRICANTE VARCHAR2(255) NOT NULL,
  FORMATO VARCHAR2(255) NOT NULL,
  TIPOPRODUTO VARCHAR2(255) NOT NULL CHECK(TIPOPRODUTO IN ('Fitofármaco', 'Adubo', 'Corretor', 'Fertilizante')),
  PRIMARY KEY (ID)
);

CREATE TABLE FERTILIZACAO (
  OPERACAOID NUMBER(10) NOT NULL,
  FATORDEPRODUCAOID NUMBER(10) NOT NULL,
  MODOFERTILIZICAODESIGNACAO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (OPERACAOID)
);

CREATE TABLE FICHATECNICA (
  ID NUMBER(10) GENERATED AS IDENTITY,
  FATORDEPRODUCAOID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE MODOFERTILIZICAO (
  DESIGNACAO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (DESIGNACAO)
);

CREATE TABLE OPERACAO (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DATA DATE NOT NULL,
  QUANTIDADE NUMBER(10),
  UNIDADE VARCHAR2(255),
  PLANTACAOID NUMBER(10) NOT NULL,
  CADERNODECAMPOID NUMBER(10) NOT NULL,
  TIPOOPERACAODESIGNACAO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PARCELA (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL,
  AREA NUMBER(10) NOT NULL,
  QUINTAID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PLANTACAO (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DATAINICIAL DATE NOT NULL,
  DATAFINAL DATE,
  QUANTIDADE NUMBER(10) NOT NULL,
  UNIDADE VARCHAR2(255) NOT NULL,
  PARCELAID NUMBER(10) NOT NULL,
  CULTURANOMECOMUM VARCHAR2(255) NOT NULL,
  CULTURAVARIEDADE VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE QUINTA (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DESIGNACAO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE REGISTOSENSOR (
  ID NUMBER(10) GENERATED AS IDENTITY,
  VALOR NUMBER(10) NOT NULL,
  DATA DATE NOT NULL,
  ESTACAOMETEOROLOGICAID NUMBER(10) NOT NULL,
  CADERNODECAMPOID NUMBER(10) NOT NULL,
  SENSORID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SENSOR (
  ID NUMBER(10) GENERATED AS IDENTITY,
  TIPOSENSORID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TIPOEDIFICIO (
  DESIGNACAO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (DESIGNACAO)
);

CREATE TABLE TIPOOPERACAO (
  DESIGNACAO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (DESIGNACAO)
);

CREATE TABLE TIPOSENSOR (
  ID NUMBER(10) GENERATED AS IDENTITY,
  DESIGNACAO VARCHAR2(255) NOT NULL,
  UNIDADE VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE Edificio ADD CONSTRAINT FKEdificio212023 FOREIGN KEY (TipoEdificioDesignacao) REFERENCES TipoEdificio (Designacao);
ALTER TABLE Plantacao ADD CONSTRAINT FKPlantacao85856 FOREIGN KEY (ParcelaID) REFERENCES Parcela (ID);
ALTER TABLE Operacao ADD CONSTRAINT FKOperacao529665 FOREIGN KEY (PlantacaoID) REFERENCES Plantacao (ID);
ALTER TABLE ElementoFicha ADD CONSTRAINT FKElementoFi602363 FOREIGN KEY (FichaTecnicaID) REFERENCES FichaTecnica (ID);
ALTER TABLE RegistoSensor ADD CONSTRAINT FKRegistoSen577174 FOREIGN KEY (EstacaoMeteorologicaID) REFERENCES EstacaoMeteorologica (ID);
ALTER TABLE Operacao ADD CONSTRAINT FKOperacao50794 FOREIGN KEY (TipoOperacaoDesignacao) REFERENCES TipoOperacao (Designacao);
ALTER TABLE RegistoSensor ADD CONSTRAINT FKRegistoSen307126 FOREIGN KEY (SensorID) REFERENCES Sensor (ID);
ALTER TABLE Sensor ADD CONSTRAINT FKSensor879684 FOREIGN KEY (TipoSensorID) REFERENCES TipoSensor (ID);
ALTER TABLE RegistoSensor ADD CONSTRAINT FKRegistoSen387930 FOREIGN KEY (CadernoDeCampoID) REFERENCES CadernoDeCampo (ID);
ALTER TABLE Operacao ADD CONSTRAINT FKOperacao671840 FOREIGN KEY (CadernoDeCampoID) REFERENCES CadernoDeCampo (ID);
ALTER TABLE Plantacao ADD CONSTRAINT FKPlantacao628054 FOREIGN KEY (CulturaNomeComum, CulturaVariedade) REFERENCES Cultura (NomeComum, Variedade);
ALTER TABLE Fertilizacao ADD CONSTRAINT FKFertilizac483896 FOREIGN KEY (OperacaoID) REFERENCES Operacao (ID);
ALTER TABLE Fertilizacao ADD CONSTRAINT FKFertilizac49592 FOREIGN KEY (ModoFertilizicaoDesignacao) REFERENCES ModoFertilizicao (Designacao);
ALTER TABLE ElementoFicha ADD CONSTRAINT FKElementoFi867111 FOREIGN KEY (ElementoDesignacao) REFERENCES Elemento (Designacao);
ALTER TABLE Edificio ADD CONSTRAINT FKEdificio681139 FOREIGN KEY (QuintaID) REFERENCES Quinta (ID);
ALTER TABLE Parcela ADD CONSTRAINT FKParcela842886 FOREIGN KEY (QuintaID) REFERENCES Quinta (ID);
ALTER TABLE EstacaoMeteorologica ADD CONSTRAINT FKEstacaoMet933281 FOREIGN KEY (QuintaID) REFERENCES Quinta (ID);
ALTER TABLE CadernoDeCampo ADD CONSTRAINT FKCadernoDeC804960 FOREIGN KEY (QuintaID) REFERENCES Quinta (ID);
ALTER TABLE AplicacaoProduto ADD CONSTRAINT FKAplicacaoP490933 FOREIGN KEY (FatorDeProducaoID) REFERENCES FatorDeProducao (ID);
ALTER TABLE FichaTecnica ADD CONSTRAINT FKFichaTecni776683 FOREIGN KEY (FatorDeProducaoID) REFERENCES FatorDeProducao (ID);
ALTER TABLE Fertilizacao ADD CONSTRAINT FKFertilizac478523 FOREIGN KEY (FatorDeProducaoID) REFERENCES FatorDeProducao (ID);
