INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'RAINHA CLAUDIA CARANGUEJEIRA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'PRESIDENT', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'STANLEY', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'ANGELENO', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'BLACK BEAUTY', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'BLACK STAR', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'BLACK GOLD', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'BLACK DIAMOND', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'BLACK AMBER', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'BLACK SPLENDOR', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'FORTUNA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'FRIAR', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'EL DORADO', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'ELEPHANT HEART', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'GOLDEN JAPAN', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'HARRY PITCHON', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'LAETITIA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'METLEY', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'MIRABELLE DE NANCY', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'QUEEN ROSE', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'RED BEAUT', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'SANTA ROSA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'SHIRO', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'SUNGOLD', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'WILSON PERFECTION', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus domestica', 'Ameixoeira', 'AUTUMN GIANT', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus armeniaca', 'Damasqueiro', 'BULIDA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus armeniaca', 'Damasqueiro', 'CANINO', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus armeniaca', 'Damasqueiro', 'LIABAUD', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus armeniaca', 'Damasqueiro', 'MAILLOT JAUNE', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Prunus armeniaca', 'Damasqueiro', 'POLONAIS', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Fevereiro a março', 'Julho a agosto');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'AKANE', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'BELGOLDEN', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'BRAVO DE ESMOLFE', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'CASA NOVA DE ALCOBAÇA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'EROVAN', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'FUJI', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'GRANNY SMITH', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'GOLDEN DELICIOUS', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'HI-EARLY', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'JONAGORED', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'LYSGOLDEN', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'MUTSU', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'PORTA DA LOJA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Janeiro', 'Abril a maio', 'Novembro a dezembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'REINETTE OU CANADA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'REINETTE OU GRAND FAY', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'RISCADINHA DE PALMELA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'ROYAL GALA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'REDCHIEF', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'STARKING', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'SUMMER RED', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'WELL'SPUR DELICIOUS', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'NOIVA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'OLHO ABERTO', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'CAMOESA ROSA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'MALÁPIO', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'GRONHO DOCE', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'PÉ DE BOI ', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'PINOVA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'PARDO LINDO', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'PIPO DE BASTO', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'PRIMA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'QUERINA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'VISTA BELLA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'GOLDEN SMOOTHEE', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'GOLDEN SUPREMA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'GLOSTER 69', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Malus domestica', 'Macieira', 'FREEDOM', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', 'Novembro a dezembro', 'Março a abril', 'Agosto a setembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO Cultura VALUES ('Daucus carota subsp. Sativus', 'Cenoura', 'Carson Hybrid', (SELECT ID FROM TipoCultura WHERE Designacao = 'Temporária'), '', '', '', '80 dias');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO Cultura VALUES ('Daucus carota subsp. Sativus', 'Cenoura', 'Red Cored Chantenay', (SELECT ID FROM TipoCultura WHERE Designacao = 'Temporária'), '', '', '', '80 dias');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO Cultura VALUES ('Daucus carota subsp. Sativus', 'Cenoura', 'Danvers Half Long', (SELECT ID FROM TipoCultura WHERE Designacao = 'Temporária'), '', '', '', '80 dias');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO Cultura VALUES ('Daucus carota subsp. Sativus', 'Cenoura', 'Imperator 58', (SELECT ID FROM TipoCultura WHERE Designacao = 'Temporária'), '', '', '', '80 dias');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO Cultura VALUES ('Daucus carota subsp. Sativus', 'Cenoura', 'Sugarsnax Hybrid', (SELECT ID FROM TipoCultura WHERE Designacao = 'Temporária'), '', '', '', '80 dias');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO Cultura VALUES ('Daucus carota subsp. Sativus', 'Cenoura', 'Nelson Hybrid', (SELECT ID FROM TipoCultura WHERE Designacao = 'Temporária'), '', '', '', '80 dias');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO Cultura VALUES ('Daucus carota subsp. Sativus', 'Cenoura', 'Scarlet Nantes', (SELECT ID FROM TipoCultura WHERE Designacao = 'Temporária'), '', '', '', '80 dias');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO Cultura VALUES ('Zea mays', 'Milho', 'MAS 24.C', (SELECT ID FROM TipoCultura WHERE Designacao = 'Temporária'), 'Abril a junho', '', '', 'Julho a setembro');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO Cultura VALUES ('Zea mays', 'Milho', 'Doce Golden Bantam', (SELECT ID FROM TipoCultura WHERE Designacao = 'Temporária'), 'Abril a junho', '', '', 'Julho a setembro');
INSERT INTO TipoCultura VALUES ('Temporária');
INSERT INTO Cultura VALUES ('Brassica rapa', 'Nabo greleiro', 'Senhora Conceição', (SELECT ID FROM TipoCultura WHERE Designacao = 'Temporária'), 'Março a setembro', '', '', 'Junho a fevereiro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Olea europaea', 'Oliveira', 'COBRANÇOSA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', '', '', 'Outubro a novembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Olea europaea', 'Oliveira', 'ARBEQUINA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', '', '', 'Outubro a novembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Olea europaea', 'Oliveira', 'HOJIBLANCA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', '', '', 'Outubro a novembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Olea europaea', 'Oliveira', 'NEGRINHA DO FREIXO', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', '', '', 'Outubro a novembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Olea europaea', 'Oliveira', 'PICUAL', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', '', '', 'Outubro a novembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Olea europaea', 'Oliveira', 'MAÇANILHA', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', '', '', 'Outubro a novembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Olea europaea', 'Oliveira', 'CONSERVA DE ELVAS', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', '', '', 'Outubro a novembro');
INSERT INTO TipoCultura VALUES ('Permanente');
INSERT INTO Cultura VALUES ('Olea europaea', 'Oliveira', 'Galega ', (SELECT ID FROM TipoCultura WHERE Designacao = 'Permanente'), '', '', '', 'Outubro a novembro');
