DROP TABLE Aplicacao CASCADE CONSTRAINTS;
DROP TABLE AplicacaoFitofarmaco CASCADE CONSTRAINTS;
DROP TABLE AplicacaoProduto CASCADE CONSTRAINTS;
DROP TABLE CadernoDeCampo CASCADE CONSTRAINTS;
DROP TABLE Cultura CASCADE CONSTRAINTS;
DROP TABLE Edificio CASCADE CONSTRAINTS;
DROP TABLE Elemento CASCADE CONSTRAINTS;
DROP TABLE ElementoFicha CASCADE CONSTRAINTS;
DROP TABLE EstacaoMeteorologica CASCADE CONSTRAINTS;
DROP TABLE FatorDeProducao CASCADE CONSTRAINTS;
DROP TABLE Fertilizacao CASCADE CONSTRAINTS;
DROP TABLE ModoFertilizacao CASCADE CONSTRAINTS;
DROP TABLE NomeEspecie CASCADE CONSTRAINTS;
DROP TABLE Operacao CASCADE CONSTRAINTS;
DROP TABLE Parcela CASCADE CONSTRAINTS;
DROP TABLE Plantacao CASCADE CONSTRAINTS;
DROP TABLE Quinta CASCADE CONSTRAINTS;
DROP TABLE RegistoSensor CASCADE CONSTRAINTS;
DROP TABLE Sensor CASCADE CONSTRAINTS;
DROP TABLE TipoCultura CASCADE CONSTRAINTS;
DROP TABLE TipoEdificio CASCADE CONSTRAINTS;
DROP TABLE TipoOperacao CASCADE CONSTRAINTS;
DROP TABLE TipoProduto CASCADE CONSTRAINTS;
DROP TABLE TipoSensor CASCADE CONSTRAINTS;

CREATE TABLE APLICACAO (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE APLICACAOFITOFARMACO (
  OPERACAOID NUMBER(10) NOT NULL,
  FATORDEPRODUCAOID NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAOID)
);

CREATE TABLE APLICACAOPRODUTO (
  FATORDEPRODUCAOID NUMBER(10) NOT NULL,
  APLICACAOID NUMBER(10) NOT NULL,
  PRIMARY KEY (FATORDEPRODUCAOID, APLICACAOID)
);

CREATE TABLE CADERNODECAMPO (
  ID NUMBER(10) NOT NULL,
  QUINTAID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CULTURA (
  ID NUMBER(10) NOT NULL,
  VARIEDADE VARCHAR2(255),
  PODA VARCHAR2(255),
  FLORACAO VARCHAR2(255),
  COLHEITA VARCHAR2(255),
  SEMENTEIRA VARCHAR2(255),
  NOMEESPECIEID NUMBER(10) NOT NULL,
  TIPOCULTURAID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE EDIFICIO (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL,
  AREA NUMBER(10),
  UNIDADE VARCHAR2(255),
  TIPOEDIFICIOID NUMBER(10) NOT NULL,
  QUINTAID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE ELEMENTO (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE ELEMENTOFICHA (
  FATORDEPRODUCAOID NUMBER(10) NOT NULL,
  ELEMENTOID NUMBER(10) NOT NULL,
  QUANTIDADE VARCHAR2(255) NOT NULL,
  PRIMARY KEY (FATORDEPRODUCAOID, ELEMENTOID)
);

CREATE TABLE ESTACAOMETEOROLOGICA (
  ID NUMBER(10) NOT NULL,
  QUINTAID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE FATORDEPRODUCAO (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL UNIQUE,
  FABRICANTE VARCHAR2(255) NOT NULL,
  FORMATO VARCHAR2(255) NOT NULL,
  TIPOPRODUTOID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE FERTILIZACAO (
  OPERACAOID NUMBER(10) NOT NULL,
  MODOFERTILIZACAOID NUMBER(10) NOT NULL,
  FATORDEPRODUCAOID NUMBER(10) NOT NULL,
  PRIMARY KEY (OPERACAOID)
);

CREATE TABLE MODOFERTILIZACAO (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE NOMEESPECIE (
  ID NUMBER(10) NOT NULL,
  NOMECOMUM VARCHAR2(255) NOT NULL,
  ESPECIE VARCHAR2(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE OPERACAO (
  ID NUMBER(10) NOT NULL,
  DATAOPERACAO DATE NOT NULL,
  QUANTIDADE NUMBER(10),
  UNIDADE VARCHAR2(255),
  PLANTACAOID NUMBER(10),
  CADERNODECAMPOID NUMBER(10) NOT NULL,
  TIPOOPERACAOID NUMBER(10) NOT NULL,
  PARCELAID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PARCELA (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL,
  AREA NUMBER(10) NOT NULL,
  QUINTAID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PLANTACAO (
  ID NUMBER(10) NOT NULL,
  DATAINICIAL DATE NOT NULL,
  DATAFINAL DATE,
  QUANTIDADE NUMBER(10) NOT NULL,
  UNIDADE VARCHAR2(255) NOT NULL,
  PARCELAID NUMBER(10) NOT NULL,
  CULTURAID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE QUINTA (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE REGISTOSENSOR (
  ID NUMBER(10) NOT NULL,
  VALOR NUMBER(10) NOT NULL,
  DATAREGISTO DATE NOT NULL,
  ESTACAOMETEOROLOGICAID NUMBER(10) NOT NULL,
  SENSORID NUMBER(10) NOT NULL,
  CADERNODECAMPOID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SENSOR (
  ID NUMBER(10) NOT NULL,
  TIPOSENSORID NUMBER(10) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TIPOCULTURA (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL UNIQUE CHECK(DESIGNACAO IN ('Permanente', 'Temporária')),
  PRIMARY KEY (ID)
);

CREATE TABLE TIPOEDIFICIO (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE TIPOOPERACAO (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE TIPOPRODUTO (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL UNIQUE,
  PRIMARY KEY (ID)
);

CREATE TABLE TIPOSENSOR (
  ID NUMBER(10) NOT NULL,
  DESIGNACAO VARCHAR2(255) NOT NULL UNIQUE,
  UNIDADE VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID)
);

ALTER TABLE Plantacao ADD CONSTRAINT FKPlantacao85856 FOREIGN KEY (ParcelaID) REFERENCES Parcela (ID);
ALTER TABLE Operacao ADD CONSTRAINT FKOperacao529665 FOREIGN KEY (PlantacaoID) REFERENCES Plantacao (ID);
ALTER TABLE RegistoSensor ADD CONSTRAINT FKRegistoSen577174 FOREIGN KEY (EstacaoMeteorologicaID) REFERENCES EstacaoMeteorologica (ID);
ALTER TABLE RegistoSensor ADD CONSTRAINT FKRegistoSen307126 FOREIGN KEY (SensorID) REFERENCES Sensor (ID);
ALTER TABLE Sensor ADD CONSTRAINT FKSensor879684 FOREIGN KEY (TipoSensorID) REFERENCES TipoSensor (ID);
ALTER TABLE RegistoSensor ADD CONSTRAINT FKRegistoSen387930 FOREIGN KEY (CadernoDeCampoID) REFERENCES CadernoDeCampo (ID);
ALTER TABLE Operacao ADD CONSTRAINT FKOperacao671840 FOREIGN KEY (CadernoDeCampoID) REFERENCES CadernoDeCampo (ID);
ALTER TABLE Plantacao ADD CONSTRAINT FKPlantacao171838 FOREIGN KEY (CulturaID) REFERENCES Cultura (ID);
ALTER TABLE Fertilizacao ADD CONSTRAINT FKFertilizac483896 FOREIGN KEY (OperacaoID) REFERENCES Operacao (ID);
ALTER TABLE Fertilizacao ADD CONSTRAINT FKFertilizac729538 FOREIGN KEY (ModoFertilizacaoID) REFERENCES ModoFertilizacao (ID);
ALTER TABLE ElementoFicha ADD CONSTRAINT FKElementoFi523793 FOREIGN KEY (ElementoID) REFERENCES Elemento (ID);
ALTER TABLE Edificio ADD CONSTRAINT FKEdificio681139 FOREIGN KEY (QuintaID) REFERENCES Quinta (ID);
ALTER TABLE Parcela ADD CONSTRAINT FKParcela842886 FOREIGN KEY (QuintaID) REFERENCES Quinta (ID);
ALTER TABLE EstacaoMeteorologica ADD CONSTRAINT FKEstacaoMet933281 FOREIGN KEY (QuintaID) REFERENCES Quinta (ID);
ALTER TABLE CadernoDeCampo ADD CONSTRAINT FKCadernoDeC804960 FOREIGN KEY (QuintaID) REFERENCES Quinta (ID);
ALTER TABLE AplicacaoProduto ADD CONSTRAINT FKAplicacaoP490933 FOREIGN KEY (FatorDeProducaoID) REFERENCES FatorDeProducao (ID);
ALTER TABLE Fertilizacao ADD CONSTRAINT FKFertilizac478523 FOREIGN KEY (FatorDeProducaoID) REFERENCES FatorDeProducao (ID);
ALTER TABLE Operacao ADD CONSTRAINT FKOperacao623592 FOREIGN KEY (TipoOperacaoID) REFERENCES TipoOperacao (ID);
ALTER TABLE Edificio ADD CONSTRAINT FKEdificio778486 FOREIGN KEY (TipoEdificioID) REFERENCES TipoEdificio (ID);
ALTER TABLE AplicacaoProduto ADD CONSTRAINT FKAplicacaoP648154 FOREIGN KEY (AplicacaoID) REFERENCES Aplicacao (ID);
ALTER TABLE ElementoFicha ADD CONSTRAINT FKElementoFi512400 FOREIGN KEY (FatorDeProducaoID) REFERENCES FatorDeProducao (ID);
ALTER TABLE FatorDeProducao ADD CONSTRAINT FKFatorDePro879583 FOREIGN KEY (TipoProdutoID) REFERENCES TipoProduto (ID);
ALTER TABLE Cultura ADD CONSTRAINT FKCultura303785 FOREIGN KEY (TipoCulturaID) REFERENCES TipoCultura (ID);
ALTER TABLE Cultura ADD CONSTRAINT FKCultura266968 FOREIGN KEY (NomeEspecieID) REFERENCES NomeEspecie (ID);
ALTER TABLE AplicacaoFitofarmaco ADD CONSTRAINT FKAplicacaoF291408 FOREIGN KEY (OperacaoID) REFERENCES Operacao (ID);
ALTER TABLE AplicacaoFitofarmaco ADD CONSTRAINT FKAplicacaoF296781 FOREIGN KEY (FatorDeProducaoID) REFERENCES FatorDeProducao (ID);
ALTER TABLE Operacao ADD CONSTRAINT FKOperacao806328 FOREIGN KEY (ParcelaID) REFERENCES Parcela (ID);