SELECT
    'drop '
    ||OBJECT_TYPE
    ||' '
    ||OBJECT_NAME
    ||';'
FROM
    USER_OBJECTS
WHERE
    OBJECT_TYPE IN ('PACKAGE', 'PACKAGE BODY', 'PROCEDURE', 'FUNCTION')
ORDER BY
    DECODE('PACKAGE BODY', 1, 2)